### ISSUE TITLE
Feature request: Define priorities for cards

### ISSUE THREAD

**Issue by crash7** [Q42/TrelloScrum#77]
Hi all,

I'm interested in having the option to define a priority for a given card (without using labels, as i using them for another thing).

Initially i would start with something like:
1. Blocker
2. Critical
3. Major
4. Minor
5. Trivial

But in the future we could extend/change this in the options menu. 
Also we could add list sorting in the future.

Any ideas? +1 or -1? Any fork that already implemented something like this?

**Comment by SeanColombo** [comment]
I tend to use color-coded Labels for this. You can have any number of Labels in Trello now.

**Comment by crash7** [comment]
@SeanColombo thanks for the input!

I'm not using labels because i usually move cards to other boards.

**Comment by gabeweaver** [comment]
@crash7 labels are copied to other boards now. I think it would be somewhat duplicitous to use anything other than Labels, since you can use labels for whatever you want, including multiple purposes. We decided to create a simple policy that reflects the color, title, and general behavior of the labeling system. It's also nice doing it this way because we can constantly improve the policy as our workflow changes and improves.

**Comment by SeanColombo** [comment]
Sounds like Labels is definitely the way to go now that they can be moved to other boards (thanks for implementing that, Trello!) :)

Will close this one out since core-Trello is handling it now. Thanks for the feedback, everyone!
