### ISSUE TITLE
Causing the card number to display

### ISSUE THREAD

**Issue by JohnKacz** [Q42/TrelloScrum#89]
The Chrome extension is displaying the card number in the board view on each card, which in turn breaks the estimation icon display. Happening on all my boards. See screenshots:

This seems to have just happened within the last 24 hours. In Chrome 45.0.2454.85 (64-bit) on Mac OSX 10.10.5

Extension enabled:
![screen shot 2015-09-04 at 9 53 12 am](https://cloud.githubusercontent.com/assets/85964/9686868/a3393b7c-52eb-11e5-9862-9454a6c6612d.png)

Extension disabled:
![screen shot 2015-09-04 at 9 53 44 am](https://cloud.githubusercontent.com/assets/85964/9686893/ca6a8926-52eb-11e5-8554-2e2e6fcc53a9.png)

**Comment by JolandaVerhoef** [comment]
Same behavior here: Iceweasel 38.1.0 (64 bit) on Debian Linux.

**Comment by JohnKacz** [comment]
Looks like the team is aware of the issue but unable to confirm which format Trello will maintain. https://github.com/Q42/TrelloScrum/commit/9bd5d0a34e2538a6f64a78b506676f7d13138f3d

**Comment by SeanColombo** [comment]
Ah, the title made me think this was another request to show the card number :)

As @JohnKacz had discovered, this was due to some Trello changes and we got it ironed out. Sorry that we didn't respond to this issue at the time & thanks for pointing this bug out! (we often see the Issues even if we forget to respond to them in the chaos of solving things)
